[package]
name = "limiga"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.5", features = ["derive"] }
limiga-core = { path = "crates/core" }
limiga-dimacs = { path = "crates/dimacs" }

[workspace]
members = ["crates/*"]
